var map = L.map('map',{zoomControl:false}).setView([-34.615889, -58.442420], 12);
L.tileLayer('https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png', {
	attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attribution">CARTO</a>'
}).addTo(map);


//ESTO NO FUNCIONABA VOLVER A PONER
// var geocoder = L.Mapzen.geocoder('mapzen-fkPfGup');
// geocoder.addTo(map);


//ADDING TO MAP
improvementRadiosMap.addTo(map);
subwayLinesMap.addTo(map);
subwayStationsMap.addTo(map);
oldStationsMap.addTo(map);
homesToBikesMap.addTo(map);
bikeToSubwayMap.addTo(map);
newStationsMap.addTo(map);



/* CSS - Cascading Style Sheet */
/* Palette color codes */
/* Palette URL: http://paletton.com/#uid=70X1q0kllll7F02ewaHsavZE5+U */

/* Feel free to copy&paste color codes to your application */


/* As hex codes */
//NARANAJA - SUBWAY
// .color-primary-0 { color: #AA8439 }	/* Main Primary color */
// .color-primary-1 { color: #000000 }
// .color-primary-2 { color: #55482F }
// .color-primary-3 { color: #FFB41F }
// .color-primary-4 { color: #FFAA00 }
//VERDE BIKE NEW
// .color-secondary-1-0 { color: #7B9F35 }	/* Main Secondary color (1) */
// .color-secondary-1-1 { color: #000000 }
// .color-secondary-1-2 { color: #44502C }
// .color-secondary-1-3 { color: #A8EE1C }
// .color-secondary-1-4 { color: #AAFF00 }
//ROSA - TIMES
// .color-secondary-2-0 { color: #882D61 }	/* Main Secondary color (2) */
// .color-secondary-2-1 { color: #000000 }
// .color-secondary-2-2 { color: #442537 }
// .color-secondary-2-3 { color: #CC187E }
// .color-secondary-2-4 { color: #FF0090 }
//AZUL- BIKE OLD
// .color-complement-0 { color: #2E4272 }	/* Main Complement color */
// .color-complement-1 { color: #000000 }
// .color-complement-2 { color: #222939 }
// .color-complement-3 { color: #244DAB }
// .color-complement-4 { color: #135AFF }



/* Generated by Paletton.com Â© 2002-2014 */
/* http://paletton.com */